added usage message, ability to specify time option, cleaned up, ...

diff --git a/src/main_test_app/test/run_tests b/src/main_test_app/test/run_tests
--- a/src/main_test_app/test/run_tests
+++ b/src/main_test_app/test/run_tests
@@ -6,13 +6,21 @@ cleanup ()
 	exit $ExitStatus
 }
 
+progname ()
+{
+	echo $(basename $0)
+}
+
+usage ()
+{
+	echo "Usage: progname [test_parameter_file] [-time]"
+}
+
 find_test_dir()
 {
-	if [ -d test ]
-	then
+	if [ -d test ]; then
 		cd test
-	elif [ -d ../../test ]
-	then
+	elif [ -d ../../test ]; then
 		cd ../../test
 	else
 		echo "Cannot find test directory - exiting ..."
@@ -24,30 +32,25 @@ set_up()
 {
 	successes=0
 	test_count=0
-	if [ ! -d bin ]
-	then
+	if [ ! -d bin ]; then
 		echo "Where's the bin directory?"
 		exit -1
 	fi
 	PATH=$PATH:./bin
-	if [ ! -r bin/testlib ]
-	then
+	if [ ! -r bin/testlib ]; then
 		echo "shell function definitions file testlib is not in bin directory - exiting ..."
 		exit -1
 	else
 		. bin/testlib
 	fi
 	type compare_numbers >/dev/null 2>&1
-	if [ $? -ne 0 ]
-	then
+	if [ $? -ne 0 ]; then
 		echo "Script compare_numbers is not in bin directory - exiting ..."
 		exit -1
 	fi
-	if [ -d ../EIFGEN/F_code -a -x ../EIFGEN/F_code/main_test ]
-	then
+	if [ -d ../EIFGEN/F_code -a -x ../EIFGEN/F_code/main_test ]; then
 		exec=../EIFGEN/F_code/main_test
-	elif [ -d ../EIFGEN/W_code -a -x ../EIFGEN/W_code/main_test ]
-	then
+	elif [ -d ../EIFGEN/W_code -a -x ../EIFGEN/W_code/main_test ]; then
 		exec=../EIFGEN/W_code/main_test
 		ln -s ../EIFGEN/W_code/melted.eif .
 	else
@@ -55,31 +58,32 @@ set_up()
 		echo "exiting ..."
 		exit -1
 	fi
-	if [ ! -r input/test_data -o ! -r input/ma -o ! -r input/stoch -o \
-		! -r input/williams ]
-	then
-		echo "Cannot find test input file - exiting ..."
-		exit -1
-	else
-		if [ $# -eq 0 ]
-		then
-			file_name_table=lib/test_files.1
-		else
-			file_name_table=$1
-			if [ ! -r $file_name_table ]
-			then
-				echo "Cannot read $file_name_table - exiting ..."
-				exit -1
-			fi
-		fi
+
+	while [ $# -gt 0 ]; do
+		case $1 in
+			-t*) exec="time $exec";;
+			-*) usage; exit ;;
+			*)
+				test_parameter_file=$1
+				if [ ! -r $test_parameter_file ]; then
+					echo "Cannot read $test_parameter_file - exiting ..."
+					ExitStatus=-1
+					exit
+				fi
+			;;
+		esac
+		shift
+	done
+
+	if [ -z "$test_parameter_file" ]; then
+		test_parameter_file=lib/test_files.1
 	fi
-	if [ -e output -a ! -d output ]
-	then
+
+	if [ -e output -a ! -d output ]; then
 		echo "Cannot create directory named output since a file already"
 		echo "exists by that name - exiting ..."
 		exit -1
-	elif [ ! -e output ]
-	then
+	elif [ ! -e output ]; then
 		mkdir output
 	fi
 }
@@ -120,8 +124,7 @@ run_test()
 	else
 		errors="Test execution of $* failed with return status $result"
 	fi
-	if [ -z "$errors" ]
-	then
+	if [ -z "$errors" ]; then
 		echo "$*" test succeeded
 		successes=$(expr $successes + 1)
 	else
@@ -135,13 +138,12 @@ trap "cleanup" 0
 trap "ExitStatus=-2 cleanup" \
 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 # ...
 
-if [ "$(basename $PWD)" != test ]
-then
+if [ "$(basename $PWD)" != test ]; then
 	find_test_dir
 fi
 
 if [ $# -gt 0 ]; then
-	set_up $1
+	set_up $*
 else
 	set_up
 fi
@@ -149,16 +151,15 @@ fi
 outputfile=output/test1.out
 
 echo "Using executable file $exec"
-set_next_test_params $file_name_table
+set_next_test_params $test_parameter_file
 while [ ! "$Tfinished" = "true" ]; do
 	echo "Runing test for $Test_name"
 	run_test $Test_name
-	set_next_test_params $file_name_table
+	set_next_test_params $test_parameter_file
 done
 
 echo "$successes out of $test_count tests succeeded."
-if [ "$successes" -eq "$test_count" ]
-then
+if [ "$successes" -eq "$test_count" ]; then
 	ExitStatus=0; cleanup
 else
 	ExitStatus=1; cleanup
