A bit of error handling/reporting

diff --git a/src/scripts/deployment/deploy_mas b/src/scripts/deployment/deploy_mas
--- a/src/scripts/deployment/deploy_mas
+++ b/src/scripts/deployment/deploy_mas
@@ -3,5 +3,15 @@
 
 basedir=$(dirname $0)
 
-perl -I $basedir $basedir/deploy_server.pl $*
-perl -I $basedir $basedir/deploy_web.pl $*
+result=0
+if perl -I $basedir $basedir/deploy_server.pl $*; then
+	if ! perl -I $basedir $basedir/deploy_web.pl $*; then
+		echo "Deployment of MAS web application failed." >&2
+		result=2
+	fi
+else
+	echo "Deployment of MAS server failed." >&2
+	result=1
+fi
+
+exit $result
