Made some improvements to the install scripts: use File:Copy instead of cp, add "use strict" and fix problems, more correct use of package/modules, etc.

diff --git a/src/scripts/deployment/deploy_mas b/src/scripts/deployment/deploy_mas
--- a/src/scripts/deployment/deploy_mas
+++ b/src/scripts/deployment/deploy_mas
@@ -14,7 +14,7 @@ if perl -I $basedir $basedir/deploy_server.pl -m $msg_file $*; then
 		if [ -r $msg_file ]; then
 			cat $msg_file >&2
 		else
-			echo "Cannot read message file: $msg_file." >&3
+			echo "Cannot read message file: $msg_file." >&2
 		fi
 	fi
 else
