Added capability for the deploy_server.pl script to write a message to a file specified in a CL argument that briefly describes how to start and stop the mas server; and added the managing of this file in deploy_mas.

diff --git a/src/scripts/deployment/deploy_mas b/src/scripts/deployment/deploy_mas
--- a/src/scripts/deployment/deploy_mas
+++ b/src/scripts/deployment/deploy_mas
@@ -2,18 +2,25 @@
 # Deploy the MAS server and web application.
 
 basedir=$(dirname $0)
+msg_file=/tmp/msg$$
 
 result=0
-if perl -I $basedir $basedir/deploy_server.pl $*; then
+if perl -I $basedir $basedir/deploy_server.pl -m $msg_file $*; then
 	if ! perl -I $basedir $basedir/deploy_web.pl $*; then
 		echo "Deployment of MAS web application failed." >&2
 		result=2
 	else
 		echo "Deployment of MAS server and web application succeeded." >&2
+		if [ -r $msg_file ]; then
+			echo "$(cat $msg_file)" >&2
+		else
+			echo "Cannot read message file: $msg_file." >&3
+		fi
 	fi
 else
 	echo "Deployment of MAS server failed." >&2
 	result=1
 fi
 
+rm -f $msg_file
 exit $result
