Began changes to ensure uniqueness of stored names
The current goal is to ensure that all stored objects (functions,
operators, analyzers, etc.) have a unique name.  Before any new
indicators or analyzers are stored, the names of any components of
these objects will be guaranteed to be unique.  (Existing
indicators_persist and generators_persist files will, of course,
need to be recreated with the new version, since they definitely
contain objects with name conflicts.)  The main reason for this
change, currently, is to ensure that the parameter-setting behavior
provided to a client (param_req, param_set_req - See
server_protocol_grammar) is correct - i.e., the specific parameter
intended to be viewed or set by the client is uniquely identified.

TRADABLE_PROCESSOR: Implement (or stub) new inherited methods:
direct_components, append_to_name.  STORABLE_SERVICES: Added
'check_for_duplicate_names' (which might want to be moved to a more
appropriate class), which uses the new 'all_components' feature of
TREE_NODE.

Began changes in the *EDITING* classes - used for creating and
changing indicators and analyzers, AKA event-generators (i.e., what
goes into the indicators_persist and generators_persist files)
to append a "clause" (or phrase) to the name to make it unique.

ctags-cron: small improvements; doc/applications/tools: 'lu'
(*_protocol*grammar lookup) convenience function.

diff --git a/bin/ctags-cron b/bin/ctags-cron
--- a/bin/ctags-cron
+++ b/bin/ctags-cron
@@ -1,22 +1,46 @@
 #!/bin/bash
+# settings: vim: expandtab
 
-seconds=60
+progname=$(basename $0)
+seconds=22
 if [ $# -gt 0 -a "$1" -gt 0 ] 2>/dev/null; then
     seconds=$1
 fi
 
-run_ctags() {
-  if [ ! -e ./tags ]; then
-    x=notags
-  else
-    x=$(find . -name '*.e' -newer tags)
-  fi
-  if [ "$x" ]; then
-    ctags -R .
-  fi
+source_files() {
+    find ./src ./src/eiffel_library/ -name '*.e'
 }
 
+run_ctags() {
+    files=$(source_files)
+    if [ -z "$files" ]; then return; fi
+    if [ ! -e ./tags ]; then
+        x=notags
+    else
+        x=$(find $files -newer tags)
+    fi
+    if [ "$x" ]; then
+        if ctags -o ntags $files; then
+            mv ./ntags ./tags
+        else
+            echo "[$progname] ctags failed" >&2
+        fi
+    fi
+}
+
+if [ -z "$LIMIT" ]; then
+    :
+elif [ "$LIMIT" -lt 0 ]; then
+    LIMIT=
+fi
+i=1
 while :; do
-  run_ctags
-  sleep $seconds
+    run_ctags
+    if [ -z "$LIMIT" ]; then
+        :
+    elif [ $i -ge "$LIMIT" ]; then
+        break
+    fi
+    sleep $seconds
+    ((++i))
 done
