Total redo: The current scheme is to copy the mas_windows.*tar.gz file, and untar it for use by inno.

diff --git a/bin/prepare_windows_setup b/bin/prepare_windows_setup
--- a/bin/prepare_windows_setup
+++ b/bin/prepare_windows_setup
@@ -1,56 +1,34 @@
 #!/bin/bash
-# Prepare for the creation of the setup-mas*.exe file by copying the latest
-# version of all files needed by the Inno setup configuration tool to create
-# the setup*.exe file.
+# Copy the MAS Windows tar file to the inno source directory and untar it
+# in prepration for making an inno setup file.
 
-Progname=$(basename $0)
+$Progname=$(basename $0)
+
+fatal() {
+	if [ ! -z "$*" ]; then
+		echo "Fatal error encountered: $*" >&2
+	fi
+	echo "Exiting ..." >&2
+	exit -1
+}
 
 usage() {
-	echo "Usage: $Progname version"
+	echo "Usage: $Progname mas-version#"
 }
 
-fail() {
-	if [ $# -gt 0 ]; then echo $* >&2;fi
-	exit 2
-}
+if [ $# -lt 1 ]; then usage; exit 1;fi
 
-if [ $# -ne 1 ]; then usage; exit 1; fi
+version=$1
+masdir=mas-${version}
+tgtdir=$HOME/development/inno_source/
+reldir=g:/suse_6_3/usr3/tmpusr2/release/$masdir
+srcbase=mas_windows${version}.tar.gz
+srcfile=$reldir/$srcbase
+if [ ! -d $reldir ]; then fatal "Cannot find directory $reldir.";fi
+if [ ! -r $srcfile ]; then fatal "Cannot tar file $srcfile.";fi
+cd $tgtdir || fatal "Could not cd to target directory: $tgtdir."
 
-if [ -z "$MAS_SOURCE_DIR" -o -z "$MAS" ]; then
-	fail "MAS_SOURCE_DIR or MAS environment variables not set."
-fi
-Version=$1
-if [ -z "$MAS_WORK_DIR" ]; then
-	MAS_WORK_DIR=e:/mas_work
-fi
-
-mastar=mas_windows${Version}.tar.gz
-mas_tar_dest=mas-${Version}
-mas_exe_src=mas_no_assert_v1.6.5
-persist_files="generators_persist indicators_persist"
-
-cd $MAS_WORK_DIR || fail "Could not 'cd' to $MAS_WORK_DIR."
-if [ ! -r $mastar ]; then fail "Cannot read $mastar."; fi
-pwd
-df ./
-tar zxvf $mastar || fail "Untarring of $mastar failed."
-cd $mas_tar_dest || fail "Could not cd to $mas_tar_dest."
-(
-	cd $MAS_SOURCE_DIR || fail "Could not 'cd' to $MAS_SOURCE_DIR."
-	pwd
-	rm -rf *
-)
-pwd
-cp -av . $MAS_SOURCE_DIR
-cd $MAS_SOURCE_DIR || fail "Could not 'cd' to $MAS_SOURCE_DIR."
-cp $MAS/build/config/windows/inno_config.iss . ||
-	fail "Failed to copy $MAS/build/config/windows/inno_config."
-cp $MAS/lib/binaries/$mas_exe_src bin/mas.exe ||
-	fail "Failed to copy $MAS/lib/binaries/$mas_exe_src."
-for f in $persist_files;do
-	cp $MAS/build/config/$f lib ||
-		fail "Failed to copy $MAS/build/config/$f."
-done
-# clean up:
-cd $MAS_WORK_DIR || fail "Could not 'cd' to $MAS_WORK_DIR."
-rm -rf $mas_tar_dest
+# Clean up old mas work directory:
+if [ -d $masdir ]; then rm -rf $masdir; fi
+cp $srcfile .
+tar zxvf $srcbase || fatal "Failed to untar $srcbase."
